
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ceras
 */
public class LogOutDialog extends javax.swing.JDialog {
    static int ADD_PORT = 2001;
    private javax.swing.JLabel IDLabel;
    HomeWindow home;
    MessageDialog messageDiag;
    FollowDialog followDiag;
    SearchDialog searchDiag;
    SentDialog sentDiag;
    String serverIP;

    /**
     * Creates new form LogOutDialog
     */
    public LogOutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void getName(String id) {
        IDLabel = new javax.swing.JLabel();
        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 19));
        IDLabel.setText(id);
        setLayout(new BorderLayout());
        IDLabel.setHorizontalAlignment(JLabel.CENTER);
        add(IDLabel, BorderLayout.NORTH);
    }
    
    public void setIP(String ip) {
        serverIP = ip;
    }
    public String getIP() {
        return serverIP;
    }
    
    public void getWindows(HomeWindow home, MessageDialog message, FollowDialog follow, SearchDialog search, SentDialog sent) {
        this.home = home;
        messageDiag = message;
        followDiag = follow;
        searchDiag = search;
        sentDiag = sent;
    }
    
    public void closeWindows() {
        if (home.isVisible()) {
            home.dispose();
        }
        JDialog[] dialogs = {messageDiag, followDiag, searchDiag, sentDiag};
        for (JDialog dialog : dialogs) {
            if (dialog.isVisible()) {
                dialog.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Are you sure you want to leave?");

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmLogOut(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelLogOut(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ConfirmLogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmLogOut
        // TODO add your handling code here:
        try {
            String host = serverIP;
            Socket s = new Socket(host, ADD_PORT);
            Scanner in = new Scanner(s.getInputStream());
            PrintWriter out = new PrintWriter(s.getOutputStream(), true);
            
            out.println("YES LOGOUT");
            System.out.println("Sent: YES LOGOUT");
            String result = in.nextLine();
            if (result.equals("Name?")) {
                String name = IDLabel.getText();
                System.out.println("Sent: " + name);
                out.println(name);
                result = in.nextLine();
                if (result.equals("LOGGED OFF")) {
                    System.out.println(result);
                    this.closeWindows();
                    JOptionPane.showMessageDialog(this, "You are now logged off");
                    AboutDialog aboutDiag = new AboutDialog(new javax.swing.JFrame(), true);
                    aboutDiag.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    LogOutDialog.this.dispose();
                    aboutDiag.setVisible(true);
                } else {
                    System.out.println("Error");
                    JOptionPane.showMessageDialog(this, "Unable to log off");
                }
            }
            in.close();
            s.close();
        }
        catch (UnknownHostException e) {
            System.err.println("Add Protocol: no such host");
        }
        catch (IOException e) {
            System.err.println("IOEXCEPTION");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_ConfirmLogOut

    private void CancelLogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelLogOut
        // TODO add your handling code here:
        LogOutDialog.this.dispose();
    }//GEN-LAST:event_CancelLogOut

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogOutDialog dialog = new LogOutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
